
name: Deploy static website

on:
  push:
    branches: 
      - '*'
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'approve final deployment (y/n)'
        required: true
jobs:
  sandbox:
    strategy:
      matrix:
        env: [sandbox, qa, stage, prod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-duration-seconds: 1200
          role-session-name: 'github-actions'

      - name: Configure AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.2
        with:
          version: 2     # default
          verbose: true # default
          arch: amd64    # allowed values: amd64, arm64
      
      - name: Terraform Init
        run: |
            cd terraform && terraform init

      - name: Terraform Check
        run: |
            cd terraform && terraform fmt -check
            terraform validate

      - name: Terraform Plan
        if: github.event_name == 'push'
        run: |
            cd terraform
            terraform workspace select ${{ matrix.env }} || terraform workspace new ${{ matrix.env }}
            terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.deploy-prod == 'y'
        run: |
            cd terraform
            terraform workspace select ${{ matrix.env }} || terraform workspace new ${{ matrix.env }}
            terraform plan -out=tfplan
            terraform apply --auto-approve tfplan

      - name: Upload Web Content
        if: github.event.inputs.deploy-prod == 'y'
        run: |
            cd src
            aws s3 sync . s3://hl-${{ matrix.env }}-tutorial/



